import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'



const maps = [
  {
    id: 1,
    name: 'Ascent',
    image: 'https://static1-br.millenium.gg/articles/9/40/79/@/84805-ascent-article_cover_bd-1.png'
  },
  {
    id: 2,
    name: 'Bind',
    image: 'https://static1-br.millenium.gg/articles/2/73/22/@/103951-icebox-valorant-article_image_t-2.png'
  }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-full w-full py-12 px-5 items-center'>
        <h1 className='text-5xl font-medium'>Mapas:</h1>

        <div className="maps flex gap-5">
          {maps.map((map) => (
            <div key={map.id}>
              <Image src={map.image} width={200} height={200} alt={map.name}/>
            </div>
          ))}

        </div>
      </main>
    </>
  )
}
